### PR TITLE
chore: cache node_modules in github actions

### PR DESCRIPTION
**Pull request by BryanPan342**
- add a section to cache node_modules

### CODE REVIEW

**Review by mattxwang — COMMENTED** [review]
After #1 gets merged and the no-lock action gets fixed, I think this is good to merge. Not sure though, maybe wait on how Actions performs after #1?

**Comment by BryanPan342** [comment]
> After #1 gets merged and the no-lock action gets fixed, I think this is good to merge. Not sure though, maybe wait on how Actions performs after #1?

yup! its just failing on the "no-lock" npm script so this should be good after #1 and just for safety I added the `pr/do-not-merge` tag

**Review by reginawang3495 — APPROVED** [review]
lgtm!

**Comment by malsf21** [comment]
Looks like mergify can't auto-merge because we modified a workflow. Going to force-merge now!

**Pull request merged**
