### PR TITLE
feat: activity 2 intro animation

### LINKED ISSUE #43: 🚀 Feature: Activity 2 Intro Animation!
* [ ] :wave: I may be able to implement this feature request

---

This is a :rocket: Feature Request

### PR DESCRIPTION
**Pull request by reginawang3495**
- animation for activity 2 intro

question:
are the images a bit blurry? i feel like they might be (my computer resolution isnt that high, does it make a difference on whoever is looking at this's computer?)

future:
- add sound, and slow down animations to go with the sound
- change intro lottie animations to be singular json with rasterized images

closes #43

### CODE REVIEW

**Review by mattxwang — COMMENTED** [review]
I'll chime in and note that the images are a little blurry for me, especially the text in the animations ("Planet and apple video") - I'm on a 3072 x 1920 Retina and a 2560 x 1440 monitor. Is the text an SVG? I think for text, if possible we can keep that as a vector (since glyphs vectorize pretty easy), though the actual images seem good to me. If not, maybe we just need to up the font size or resolution when making the original animiation.

**Comment by reginawang99** [comment]
@mattxwang 
ty for the feedback, ill change them to vectorized and see how it turns out. unforutnatly its not svgs cuz AE doesnt support them, but i can just export as AI and hopefuly itll be good/same

**Review by mattxwang — CHANGES_REQUESTED** [review]
Ooh okay, looks good! I think the merge is also pretty clean, it resolved some `yarn.lock` issues 😊  the animations definitely look smoother and more crisp. 

last thing on my end (and something that we can get other opinions on) is using `<h2>` and `<b>` to apply styling; I think it may be better to maintain semantic HTML (with header descending, etc.). Any thoughts?

**Comment by reginawang99** [comment]
makes sense! yea i agree, it'd also help with keeping the styling consistent. im currently working on a pr for making carousel and stuffs more consistent/other cleanup so maybe it'd be good to put in that pr? what do you think?

**Review by mattxwang — APPROVED** [review]
Oh gotcha! If you're planning on addressing this in another PR, that's my only complaint here; since you're on a time crunch, I think this is GTM!

**Pull request merged**
